- name: install nagios core dependencies packages on ubuntu
  apt:
    name:
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip
    state: latest
    update_cache: yes

- name: add group nagcmd
  group:
    name: nagcmd
    state: present

- name: add user nagios
  user:
    name: nagios
    group: nagcmd
