---
# tasks file for eservice_debian
- name: INSTALL vsftpd
  apt:
    name: vsftpd
    state: latest
    update_cache: yes

- name: STOP FIREWALL
  service:
    name: ufw
    state: stopped
    enabled: no

- name: CREATE FTP USER
  user:
    name: wLodriga
    password: $5$bP4vEcN7aBPJ9DOF$9kxGu1SSSNj999c1Dg3IRwINiirj689CuQLvBDoYc6NWH.A
    comment: "Created User!"

- name: ADD DENY USER IN /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers wLodriga"
  register: ssh_config

- name: RESTART SSHD SERVICE
  service:
    name: sshd
    state: restarted
  when: ssh_config.changed

- name: CREATE FTP DIRECTORY
  file:
    path: /home/wLodriga/ftp
    state: directory
    owner: wLodriga
    group: wLodriga
    mode: '0555'

- name: CREATE FTP DIRECTORY FILES
  file:
    path: /home/wLodriga/ftp/files
    state: directory
    owner: wLodriga
    group: wLodriga

- name: COPY vsftpd.conf
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: RESTART vsftpd.conf
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
