--- 

- name: centos
  hosts:
    - centos
  vars_files:
    - config.yaml
  roles:
    - cprelims
    - cftp
    - cmotd
    - cnagios

- name: debian
become: true
hosts:
- debian
vars_files:
- config.yaml
roles:
    - debprelims
    - debftp
    - debmotd
    - debnagios

#- name: Fedora
#  become: true
 # hosts:
  #    -fedora
  #vars_files:
  #     config.yaml
  #roles:
   #   - fedora-prelim
    #  - fedora-ftp
     # - fedora-motd
      #- fedora-nagios
